ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      org.iglaz.HttpKt.configureHttp
      org.iglaz.SerializationKt.configureSerialization
      org.iglaz.PostgresKt.configurePostgres
      org.iglaz.ExposedKt.configureExposed
      org.iglaz.StatusPagesKt.configureStatusPages
      org.iglaz.ResourcesKt.configureResources
      org.iglaz.RequestValidationKt.configureRequestValidation
      org.iglaz.RoutingKt.configureRouting
    ]
  }
}