ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      org.iglaz.battlereport.HttpKt.configureHttp
      org.iglaz.battlereport.SerializationKt.configureSerialization
      org.iglaz.battlereport.PostgresKt.configurePostgres
      org.iglaz.battlereport.ExposedKt.configureExposed
      org.iglaz.battlereport.StatusPagesKt.configureStatusPages
      org.iglaz.battlereport.ResourcesKt.configureResources
      org.iglaz.battlereport.RequestValidationKt.configureRequestValidation
      org.iglaz.battlereport.RoutingKt.configureRouting
    ]
  }
}